### ISSUE TITLE
Hello, sorry if this is random.

### ISSUE THREAD

**Issue by AdamFriska** [TheIndra55/MinecartSharp#1]
Hello the Indra! i've always liked your SpigotBoard,
i know yPedx took over the SpigotBoard but he's inactive and hard to reach...

> The Major problem of his Continued SpigotBoard is, the Update or Refresh Interval.
> It takes 5-20seconds to refresh our Money Balance, or our Rank when promoted or Demoted.

But, what i like from SpigotBoard is it's actually Compatible with ALL Minercaft Versions!
starting from 1.8 until 1.14.3

Other Scoreboard Plugins get Buggy when running on Versions below 1.14.3

Please if i may have your discord reply to this Thred :"),
i'm so desperate to have a working SpigotBoard with Fixed Update Interval.

here is his Github link. 
https://github.com/yPedx/SpigotBoard

Warm Regards from-
Adam~.

**Comment by TheIndra55** [comment]
Oh hello..

If this only happens with yPed's version then not much i can do, you can use my latest version or contact yPed directly

**Comment by AdamFriska** [comment]
Yeah I'm very sorry that i posted on the wrong repo, since your board repo isn't available, so this is the least i can do... yPedx is inactive on Github, is there any way to find or contact him? Thank you! Oh i also added your discord, so i think it'll be easier to talk there ^^. My discord is Adam the Nice Man, thank you!

**Comment by TheIndra55** [comment]
He seems active on github though, next time contact the orginal author not me in a totally unrelated repo
